version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_test_redis
    restart: always
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: appdb
    ports:
    - "5458:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7  
    container_name: redis_test
    restart: always
    ports:
    - "6379:6379"  